In [1]:
print("hello")

hello

In [2]:
import numpy as np
import pandas as pd

Loading the Data

In [5]:
df=pd.read_csv(r"C:\Users\ak038\OneDrive\Desktop\Casmpus X\data\FIFA_World_Cup_Champions_1930_2022.csv")

How big is the Data

In [7]:
df.shape

(22, 23)

How does the data Look like in columns.

In [9]:
df.head()

,year,host_country,host_city_final,stadium,winner,runner_up,winner_captain,winner_head_coach,win_method,winner_goals,...,matches_played,winner_titles_after_win,continent_winner,golden_ball,golden_boot,best_young_player,golden_glove,top_scorer_goals,mascot,official_ball
0,1930,Uruguay,Montevideo,Estadio Centenario,Uruguay,Argentina,José Nasazzi,Alberto Suppici,Regular Time,4,...,18,1,South America,NaN,Guillermo Stábile,NaN,NaN,8,NaN,T-Model
1,1934,Italy,Rome,Stadio Nazionale PNF,Italy,Czechoslovakia,Gianpiero Combi,Vittorio Pozzo,Extra Time,2,...,17,1,Europe,NaN,Oldřich Nejedlý,NaN,NaN,5,NaN,Federale 102
2,1938,France,Paris,Stade Olympique de Colombes,Italy,Hungary,Giuseppe Meazza,Vittorio Pozzo,Regular Time,4,...,18,2,Europe,NaN,Leônidas,NaN,NaN,7,NaN,Allen
3,1950,Brazil,Rio de Janeiro,Maracanã,Uruguay,Brazil,Obdulio Varela,Juan López Fontana,Regular Time,2,...,22,2,South America,NaN,Ademir,NaN,NaN,9,NaN,Super Duplo T
4,1954,Switzerland,Bern,Wankdorf Stadium,West Germany,Hungary,Fritz Walter,Sepp Herberger,Regular Time,3,...,26,1,Europe,NaN,Sándor Kocsis,NaN,NaN,11,NaN,Swiss World Champion

In [10]:
df.sample(5)

,year,host_country,host_city_final,stadium,winner,runner_up,winner_captain,winner_head_coach,win_method,winner_goals,...,matches_played,winner_titles_after_win,continent_winner,golden_ball,golden_boot,best_young_player,golden_glove,top_scorer_goals,mascot,official_ball
16,2002,South Korea/Japan,Yokohama,International Stadium Yokohama,Brazil,Germany,Cafu,Luiz Felipe Scolari,Regular Time,2,...,64,5,South America,Oliver Kahn,Ronaldo,NaN,Oliver Kahn,8,Ato,Korea/Japan Fevernova
17,2006,Germany,Berlin,Olympiastadion,Italy,France,Fabio Cannavaro,Marcello Lippi,Penalties,1,...,64,4,Europe,Zinedine Zidane,Miroslav Klose,Lukas Podolski,Gianluigi Buffon,5,Goleo + Pille,Teamgeist
6,1962,Chile,Santiago,Estadio Nacional,Brazil,Czechoslovakia,Mauro,Aymoré Moreira,Regular Time,3,...,32,2,South America,NaN,Flórián Albert,NaN,NaN,4,NaN,Crack
12,1986,Mexico,Mexico City,Estadio Azteca,Argentina,West Germany,Diego Maradona,Carlos Bilardo,Regular Time,3,...,52,2,South America,Diego Maradona,Gary Lineker,NaN,NaN,6,Pique,Azteca México
1,1934,Italy,Rome,Stadio Nazionale PNF,Italy,Czechoslovakia,Gianpiero Combi,Vittorio Pozzo,Extra Time,2,...,17,1,Europe,NaN,Oldřich Nejedlý,NaN,NaN,5,NaN,Federale 102

Are there any missing values

In [11]:
df.isnull().sum()

year                        0
host_country                0
host_city_final             0
stadium                     0
winner                      0
runner_up                   0
winner_captain              0
winner_head_coach           0
win_method                  0
winner_goals                0
runner_up_goals             0
attendance                  0
total_teams                 0
matches_played              0
winner_titles_after_win     0
continent_winner            0
golden_ball                11
golden_boot                 0
best_young_player          17
golden_glove               14
top_scorer_goals            0
mascot                      7
official_ball               0
dtype: int64

How does the look Mathematically?

In [12]:
df.describe()

,year,winner_goals,runner_up_goals,attendance,total_teams,matches_played,winner_titles_after_win,top_scorer_goals
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,1978.909091,2.636364,1.136364,81534.636364,22.227273,43.818182,2.227273,7.136364
std,27.738419,1.292670,0.888844,26831.765955,7.602830,17.632860,1.231794,2.188617
min,1930.000000,0.000000,0.000000,45000.000000,13.000000,17.000000,1.000000,4.000000
25%,1959.000000,2.000000,0.250000,68759.250000,16.000000,32.000000,1.000000,6.000000
50%,1980.000000,3.000000,1.000000,76374.500000,20.000000,45.000000,2.000000,6.000000
75%,2001.000000,3.750000,2.000000,89741.500000,32.000000,64.000000,3.000000,8.000000
max,2022.000000,5.000000,3.000000,173850.000000,32.000000,64.000000,5.000000,13.000000

Are ther Duplicates Data?

In [15]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
dtype: bool

What is the Correlation Between cols

In [23]:
df.corr(numeric_only=True)

,year,winner_goals,runner_up_goals,attendance,total_teams,matches_played,winner_titles_after_win,top_scorer_goals
year,1.000000,-0.415314,-0.291116,0.086831,0.913915,0.970050,0.523261,-0.331581
winner_goals,-0.415314,1.000000,0.708325,-0.157719,-0.422419,-0.418780,-0.513836,0.540139
runner_up_goals,-0.291116,0.708325,1.000000,-0.055124,-0.328948,-0.359902,-0.377596,0.430600
attendance,0.086831,-0.157719,-0.055124,1.000000,-0.059504,0.018760,0.096213,0.076465
total_teams,0.913915,-0.422419,-0.328948,-0.059504,1.000000,0.955832,0.507779,-0.399738
matches_played,0.970050,-0.418780,-0.359902,0.018760,0.955832,1.000000,0.523784,-0.359633
winner_titles_after_win,0.523261,-0.513836,-0.377596,0.096213,0.507779,0.523784,1.000000,-0.188677
top_scorer_goals,-0.331581,0.540139,0.430600,0.076465,-0.399738,-0.359633,-0.188677,1.000000

In [24]:
df.columns

Index(['year', 'host_country', 'host_city_final', 'stadium', 'winner',
       'runner_up', 'winner_captain', 'winner_head_coach', 'win_method',
       'winner_goals', 'runner_up_goals', 'attendance', 'total_teams',
       'matches_played', 'winner_titles_after_win', 'continent_winner',
       'golden_ball', 'golden_boot', 'best_young_player', 'golden_glove',
       'top_scorer_goals', 'mascot', 'official_ball'],
      dtype='str')

In [28]:
df.corr(numeric_only=True)["winner_goals"]

year                      -0.415314
winner_goals               1.000000
runner_up_goals            0.708325
attendance                -0.157719
total_teams               -0.422419
matches_played            -0.418780
winner_titles_after_win   -0.513836
top_scorer_goals           0.540139
Name: winner_goals, dtype: float64

In [32]:
numeric_cols=df.select_dtypes(include="number")
numeric_cols

,year,winner_goals,runner_up_goals,attendance,total_teams,matches_played,winner_titles_after_win,top_scorer_goals
0,1930,4,2,68346,13,18,1,8
1,1934,2,1,55000,16,17,1,5
2,1938,4,2,45000,15,18,2,7
3,1950,2,1,173850,13,22,2,9
4,1954,3,2,62500,16,26,1,11
5,1958,5,2,49737,16,35,1,13
6,1962,3,1,68679,16,32,2,4
7,1966,4,2,96924,16,32,1,9
8,1970,4,1,107412,16,32,3,10
9,1974,2,1,78200,16,38,2,7
10,1978,3,1,71483,16,38,1,6
11,1982,3,1,90000,24,52,3,6
12,1986,3,2,114600,24,52,2,6
13,1990,1,0,73603,24,52,3,6
14,1994,0,0,94194,24,52,4,6
15,1998,3,0,80000,32,64,1,6
16,2002,2,0,69029,32,64,5,8
17,2006,1,1,69000,32,64,4,5
18,2010,1,0,84490,32,64,1,5
19,2014,1,0,74738,32,64,4,6
20,2018,4,2,78011,32,64,2,6
21,2022,3,3,88966,32,64,3,8